[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"

[env]
TF_CPP_MIN_LOG_LEVEL = "2"
CUDA_VISIBLE_DEVICES = ""
OMP_NUM_THREADS = "4"